services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    networks: # به چه نتورکایی وصل بشه
      - main
    ports: # تنظیم پورت‌ها
      - "5672:5672"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    container_name: celery_worker
    command: "celery -A config worker -l INFO"
    depends_on: # این کانتینر به کانتینرهای زیر وابسته‌س (تا اونا بالا نیومدن این هم بالا نیاد)
      - app
      - rabbitmq
      - postgres
    build: .
    environment:
      - C_FORCE_ROOT="true" # اگه سلری به عنوان روت اجرا بشه ارور نده
    networks:
      - main
    restart: always

  app:
    container_name: app
    build: . # از روی همین دایرکتوری‌ای که هستیم یه کانتینر بساز
    command: sh -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000" # اجرای مایگریت
    volumes:
      - .:/code/
    depends_on:
      - postgres
      - rabbitmq
    expose: # از خارج از نتورک به این پورت دسترسی نداشته باشند
      - "8000"
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main:

volumes:
  postgres_data:
